Welcome to University of Colorado Boulder Research Computing!

Full documentation is available in our user guide at
https://www.rc.colorado.edu/support/user-guide. If you have a question
that's not answered there, contact us at rc-help@colorado.edu.

A number of directories have been created for you already:

* `/home/$USER`, your home directory
* `/projects/$USER`, your project directory
  
Run the command `module avail` to see a list of available software.

To prevent this README from being displayed at login, edit your
`.bash_profile` or `.login` files.

---------------------------------- Compilers -----------------------------------
   aocc/3.1.0 (D)    gcc/11.2.0     (D)    nvhpc_sdk/2021.213
   aocc/3.2.0        gcc/13.2.0            nvhpc_sdk/2022.229
   gcc/10.3.0        intel/2022.1.2 (m)    nvhpc_sdk/2023.233 (D)

--------------------------- Independent Applications ---------------------------
   R/3.6.3                        mambaforge/23.1.0-1
   R/4.2.2                        mathematica/9.0
   R/4.4.0               (D)      mathematica/11.1.0   (D)
   allinea/6.0.4         (m)      matlab/R2018b
   anaconda/2020.11               matlab/R2019b
   anaconda/2022.10               matlab/R2020b
   anaconda/2023.09      (D)      matlab/R2021b        (D)
   antlr/4.13.1                   matlab/R2022b
   arm-forge/19.1.3      (m)      matlab/R2023b
   autotools/2.69                 maven/3.8.1
   autotools/2.71        (D)      ncl/6.3.0
   chimerax/1.2.5                 nco/4.8.1
   clustershell/1.9.2             papi/5.4.3
   cmake/3.5.2                    papi/5.5.1           (D)
   cmake/3.9.2                    paraview/5.0.1
   cmake/3.14.1                   paraview/5.6.0
   cmake/3.20.2                   paraview/5.9.0
   cmake/3.25.0                   paraview/5.10.0      (D)
   cmake/3.27.7          (D)      pdtoolkit/3.22
   cube/3.4.3                     pdtoolkit/3.25.1     (D)
   cube/4.3.4            (D)      perl/5.16.3
   cuda/11.2             (g)      perl/5.24.0          (D)
   cuda/11.3             (g)      perl/5.28.1
   cuda/11.4             (g)      perl/5.36.0
   cuda/11.8             (g)      pigz/2.7
   cuda/12.1.1           (g,D)    python/2.7.18
   cudnn/8.1             (g)      python/3.10.2        (D)
   cudnn/8.2             (g)      qt/5.6.0
   cudnn/8.6             (g,D)    qt/5.9.1
   curc-quota/latest              qt/5.15              (D)
   dmtcp/2.6.0                    rclone/1.58.0
   eigen/3.4.0                    rhel7for8/1.0
   emacs/25.3                     rocm/5.2.3           (g)
   emacs/27.2            (D)      rocm/5.3.0           (g)
   expat/2.1.1                    rocm/5.5.0           (g)
   expat/2.3.0           (D)      rocm/5.6.0           (g,D)
   ffmpeg/4.4                     ruby/2.3.1
   gdb/8.1                        ruby/3.0.0           (D)
   gdb/10.1              (D)      singularity/3.6.4    (D)
   ghostscript/9.56.0             singularity/3.7.4
   git-lfs/3.1.2                  slurmtools/0.0.1
   git/2.31.0                     spack/0.20.1
   gmsh/2.16.0                    subversion/1.8.16
   gmsh/4.11.1           (D)      subversion/1.10.2
   gnu_parallel/20160622          subversion/1.14.1    (D)
   gnu_parallel/20210322 (D)      tcltk/8.6.5
   gnuplot/5.4.3                  tcltk/8.6.11         (D)
   idl/8.7                        tdom/0.8.3
   imagemagick/6.9.12             tdom/0.9.2           (D)
   jdk/1.7.0                      texlive/2021
   jdk/1.8.0_91                   totalview/2016.06.21
   jdk/1.8.0_281                  ucx/1.10.1
   jdk/1.8.0                      ucx/1.12.1           (D)
   jdk/18.0.1.1          (D)      udunits/2.2.20
   julia/0.6.2                    udunits/2.2.24
   julia/1.6.0                    udunits/2.2.25
   julia/1.6.6                    udunits/2.2.28       (D)
   julia/1.8.1                    valgrind/3.11.0
   julia/1.9.4                    valgrind/3.17.0      (D)
   julia/1.10.0                   vapor/3.9.1
   julia/1.10.2          (D)      vtf3/1.43
   lftp/4.8.4                     zip/rhel7
   loadbalance/0.2

-------------------------------- Bioinformatics --------------------------------
   alphafold/2.2.0         cutadapt/4.2            plink2/2.00a2.3
   alphafold/2.3.1  (D)    fastqc/0.11.9           qiime2/2023.5
   bamtools/2.5.2          gatk/4.3.0.0            qiime2/2024.2_amplicon (D)
   bbtools/39.01           homer/4.11              samtools/1.16.1
   bcftools/1.16           htslib/1.16             sra-toolkit/3.0.0
   bedtools/2.29.1         multiqc/1.14            star/2.7.10b
   bowtie2/2.5.0           nextflow/22.10.6        trimmomatic/0.39
   bwa/0.7.17              nextflow/23.04   (D)
   cellranger/7.1.0        picard/2.27.5

---------------------------- Lmod Internal Modules -----------------------------
   StdEnv    lmod    settarg

--------------------------------- CU Licensed ----------------------------------
   CST/2021                 ansys/AnsysEM22.2              (D)
   abaqus/V6R2019x          ansys/AnsysEM23.1
   altairfeko/2019.2        coreform/Coreform-Cubit-2021.5
   altairfeko/2023.1 (D)    gaussian/g16_c.02
   ams/2023.101             gridpro/8.2
   ansys/AnsysEM21.2        trelis/16.3.6

  Where:
   D:  Default Module
   g:  built for GPU
   m:  built for host and native MIC

If the avail list is too long consider trying:

"module --default avail" or "ml -d av" to just list the default modules.
"module overview" or "ml ov" to display the number of modules for each name.

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching
any of the "keys".


Warning: Cannot perform Hydrogen sampling with GPU-Omega: GPU-Omega disabled.
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc79800000a95'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc7dd00000a96'
Warning: Cannot perform Hydrogen sampling with GPU-Omega: GPU-Omega disabled.
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc7e200000a97'
Warning: Cannot perform Hydrogen sampling with GPU-Omega: GPU-Omega disabled.
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc7f300000a98'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc7f900000a99'
Warning: Cannot perform Hydrogen sampling with GPU-Omega: GPU-Omega disabled.
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000053fc78b00000a9a'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000054fd01c00000a9b'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000055fd8e600000a9c'
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-08-09 14:08:46,869: Setting CUDA platform to use precision model 'mixed'.
2024-08-09 14:08:46,972: Reading phase solvent1
2024-08-09 14:08:47,391: WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future releases
2024-08-09 14:08:47,439: Reading phase solvent2
2024-08-09 14:08:47,455: WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future releases
2024-08-09 14:08:48,702: Protocol failed to execute: 265c7378309c4355aa01d60af70d3fca|run_solvation_yank
2024-08-09 14:08:48,702: Protocol failed to execute: 265c7378309c4355aa01d60af70d3fca|conditional_group
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000055fd8e800000a9d'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000055fd8af00000a9e'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000056fe13700000a9f'
Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 591, in _run_server
    server.serve_forever()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/managers.py", line 184, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/projects/bamo6610/software/anaconda/env/openff-sage/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000056fe13a00000aa0'
{
  "@type": "openff.evaluator.datasets.datasets.PhysicalPropertyDataSet",
  "properties": []
}
It finished
JobID           JobName    CPUTime    Elapsed 
------------ ---------- ---------- ---------- 
17579867     sys/dashb+   01:57:46   01:57:46 
17579867.ba+      batch   01:57:47   01:57:47 
17579867.ex+     extern   01:57:46   01:57:46 
17580656     sfe_test_+   00:05:31   00:05:31 
17580656.ba+      batch   00:05:30   00:05:30 
17580656.ex+     extern   00:05:31   00:05:31 
17580743     sfe_test_+   00:00:18   00:00:18 
17580743.ba+      batch   00:00:18   00:00:18 
17580743.ex+     extern   00:00:18   00:00:18 
17580755     sfe_test_+   00:00:28   00:00:28 
17580755.ba+      batch   00:00:28   00:00:28 
17580755.ex+     extern   00:00:28   00:00:28 
17580756     sfe_test_+   00:00:09   00:00:09 
17580756.ba+      batch   00:00:09   00:00:09 
17580756.ex+     extern   00:00:09   00:00:09 
17580757     sfe_test_+   00:00:06   00:00:06 
17580757.ba+      batch   00:00:06   00:00:06 
17580757.ex+     extern   00:00:06   00:00:06 
17580796     sys/dashb+   02:45:00   00:41:15 
17580796.ba+      batch   02:45:04   00:41:16 
17580796.ex+     extern   02:45:00   00:41:15 
17581196     sfe_test_+   00:01:32   00:01:32 
17581196.ba+      batch   00:01:32   00:01:32 
17581196.ex+     extern   00:01:32   00:01:32 
17581601     sfe_test_+   00:00:25   00:00:25 
17581601.ba+      batch   00:00:25   00:00:25 
17581601.ex+     extern   00:00:25   00:00:25 
17581603     sfe_test_+   00:00:08   00:00:08 
17581603.ba+      batch   00:00:08   00:00:08 
17581603.ex+     extern   00:00:08   00:00:08 
17581605     sfe_test_+   00:00:06   00:00:06 
17581605.ba+      batch   00:00:06   00:00:06 
17581605.ex+     extern   00:00:06   00:00:06 
17581607     sfe_test_+   00:00:09   00:00:09 
17581607.ba+      batch   00:00:09   00:00:09 
17581607.ex+     extern   00:00:09   00:00:09 
17581608     sfe_test_+   00:01:19   00:01:19 
17581608.ba+      batch   00:01:19   00:01:19 
17581608.ex+     extern   00:01:19   00:01:19 
17581614     sys/dashb+   02:28:04   00:37:01 
17581614.ba+      batch   02:28:08   00:37:02 
17581614.ex+     extern   02:28:04   00:37:01 
17581615     conda_test   00:00:16   00:00:16 
17581615.ba+      batch   00:00:16   00:00:16 
17581615.ex+     extern   00:00:16   00:00:16 
17581616     conda_test   00:00:05   00:00:05 
17581616.ba+      batch   00:00:05   00:00:05 
17581616.ex+     extern   00:00:05   00:00:05 
17581618     sfe_test_+   00:01:15   00:01:15 
17581618.ba+      batch   00:01:15   00:01:15 
17581618.ex+     extern   00:01:15   00:01:15 
17581624     sfe_test_+   00:01:20   00:01:20 
17581624.ba+      batch   00:01:20   00:01:20 
17581624.ex+     extern   00:01:20   00:01:20 
17581636     sfe_test_+   00:01:14   00:01:14 
17581636.ba+      batch   00:01:14   00:01:14 
17581636.ex+     extern   00:01:14   00:01:14 
17581637     sys/dashb+   02:07:40   00:31:55 
17581637.ba+      batch   02:07:40   00:31:55 
17581637.ex+     extern   02:07:40   00:31:55 
17581738     sfe_test_+   00:02:19   00:02:19 
17581738.ba+      batch   00:02:19   00:02:19 
17581738.ex+     extern   00:02:19   00:02:19 
